### ISSUE TITLE
Hideout helper fails to parse certain .hideout files

### ISSUE THREAD

**Issue by john-m-liu** [Jukkales/PoE-Hideout-Helper#1]
First off, thanks for making this! The first time I tried this it worked out great, turning what would have taken hours into minutes. I tried it a second time, but selecting a file I downloaded from poe.house (attached, rename extension to .hideout) shows 0 decorations. I tried some basic things like adding a newline at the end of the file and removing spaces/non-alphanumeric characters in the file name, but with the same result. Do you know what could be going on?
[Starry Refuge (Main Version).txt](https://github.com/Jukkales/PoE-Hideout-Helper/files/4679584/Starry.Refuge.Main.Version.txt)

**Comment by Jukkales** [comment]
Looks like that poe.house is changing the encoding of the files. The PoE client is creating files with UTF-16 (or 'UCS-2 LE-BOM' :D) encoding to fully support chinese language. Hideouts downloaded from poe.house are encoded with UTF-8.

For example you file in the right encoding is working: [Starry.Refuge.Main.Version.hideout-utf16.txt](https://github.com/Jukkales/PoE-Hideout-Helper/files/4680672/Starry.Refuge.Main.Version.hideout-utf16.txt)

I will add a failover the the loader to support UTF-8.

**Comment by Jukkales** [comment]
It should be fixed with Version 1.2. 
Would you please try it again? :)

**Comment by john-m-liu** [comment]
That fixed it. Thanks for getting on this so fast!
